# Tarea 3
Crear una sola base de datos que tenga todas las tablas de los archivos anteriores (usando las herramientas aprendidas en 2). Haz una para la temperatura, y otra para las lluvias.

In [3]:
import numpy as np
import math as mt
import matplotlib.pyplot as plt
import pandas as pd
import requests
import os

In [4]:
#Cargamos los Datos de los archivos
path_ll_18 = '/home/echeveste/Mis_trabajos/analisis_datos/da2019-Oscar2401/Semana2/Tareas/dato_temperaturas_lluvia/201801010000Lluv.csv'
path_Mx_18 = '/home/echeveste/Mis_trabajos/analisis_datos/da2019-Oscar2401/Semana2/Tareas/dato_temperaturas_lluvia/201801010000TMax.csv'
path_Mm_18 = '/home/echeveste/Mis_trabajos/analisis_datos/da2019-Oscar2401/Semana2/Tareas/dato_temperaturas_lluvia/201801010000TMin.csv'
path_Md_18 = '/home/echeveste/Mis_trabajos/analisis_datos/da2019-Oscar2401/Semana2/Tareas/dato_temperaturas_lluvia/201801010000TMed.csv'
path_ll_19 = '/home/echeveste/Mis_trabajos/analisis_datos/da2019-Oscar2401/Semana2/Tareas/dato_temperaturas_lluvia/201905010000Lluv.csv'
path_Mx_19 = '/home/echeveste/Mis_trabajos/analisis_datos/da2019-Oscar2401/Semana2/Tareas/dato_temperaturas_lluvia/201901010000TMax.csv'
path_Mm_19 = '/home/echeveste/Mis_trabajos/analisis_datos/da2019-Oscar2401/Semana2/Tareas/dato_temperaturas_lluvia/201901010000TMin.csv'
path_Md_19 = '/home/echeveste/Mis_trabajos/analisis_datos/da2019-Oscar2401/Semana2/Tareas/dato_temperaturas_lluvia/201901010000TMed.csv'

In [50]:
lluvias_2018 = pd.read_csv(path_ll_18,encoding='latin-1')
Maxima_2018 = pd.read_csv(path_Mx_18,encoding='latin-1')
Minima_2018 = pd.read_csv(path_Mm_18,encoding='latin-1')
Media_2018 = pd.read_csv(path_Md_18,encoding='latin-1')
lluvias_2019 = pd.read_csv(path_ll_19,encoding='latin-1')
Maxima_2019 = pd.read_csv(path_Mx_19,encoding='latin-1')
Minima_2019 = pd.read_csv(path_Mm_19,encoding='latin-1')
Media_2019 = pd.read_csv(path_Md_19,encoding='latin-1')

In [51]:
lluvias_2018 = lluvias_2018.rename(columns={'ESTADO' : 'EDO'})
display(lluvias_2018.head(),lluvias_2019.head())

          LON        LAT  EDO CLAVE_SIH                       NOMBRE   ENE
0 -102.309722  21.895000  AGS     AGSAG         Aguascalientes, Ags.  25.8
1 -102.466944  22.188611  AGS     ANVAG  Cincuenta Aniversario, Ags.  58.6
2 -102.712222  21.849167  AGS  CALVILLO          Calvillo, Ags. SMN*  56.0
3 -102.676944  21.997500  AGS     CDRAG            La Codorniz, Ags.  50.0
4 -102.197222  22.007222  AGS     CHOAG           Cañada Honda, Ags.  17.2

          LON        LAT  EDO CLAVE_SIH                       NOMBRE   MAY
0 -102.309722  21.895000  AGS     AGSAG         Aguascalientes, Ags.  2.12
1 -102.466944  22.188611  AGS     ANVAG  Cincuenta Aniversario, Ags.  4.20
2 -102.184167  21.738611  AGS     BRTAG            San Bartolo, Ags.  0.00
3 -102.712222  21.849167  AGS  CALVILLO          Calvillo, Ags. SMN*  5.32
4 -102.676944  21.997500  AGS     CDRAG            La Codorniz, Ags.  0.00

In [101]:
lluvias_2018['AÑO'] = pd.Series(2018*np.ones_like(lluvias_2018['EDO']))
lluvias_2019['AÑO'] = pd.Series(2019*np.ones_like(lluvias_2019['EDO']))

In [102]:
lluvias_1 = pd.concat([lluvias_2018,lluvias_2019 ],sort=False)[['AÑO','LON', 'LAT', 'EDO', 'CLAVE_SIH', 'NOMBRE', 'ENE', 'MAY']]

In [103]:
lluvias_1

,AÑO,LON,LAT,EDO,CLAVE_SIH,NOMBRE,ENE,MAY
0,2018,-102.309722,21.895000,AGS,AGSAG,"Aguascalientes, Ags.",25.8,NaN
1,2018,-102.466944,22.188611,AGS,ANVAG,"Cincuenta Aniversario, Ags.",58.6,NaN
2,2018,-102.712222,21.849167,AGS,CALVILLO,"Calvillo, Ags. SMN*",56.0,NaN
3,2018,-102.676944,21.997500,AGS,CDRAG,"La Codorniz, Ags.",50.0,NaN
4,2018,-102.197222,22.007222,AGS,CHOAG,"Cañada Honda, Ags.",17.2,NaN
5,2018,-102.189167,21.826667,AGS,CLVAG,"Calvillito, Ags.",13.5,NaN
6,2018,-102.000000,21.896389,AGS,CNSAG,"Los Conos, Ags.",51.5,NaN
7,2018,-102.296667,22.362778,AGS,CSOAG,"Cosio, Ags.",35.5,NaN
8,2018,-102.788333,21.807500,AGS,MNLAG,"Media Luna, Ags.",48.9,NaN
9,2018,-102.371667,21.780000,AGS,NGRAG,"El Niagara, Ags.",25.4,NaN
10,2018,-102.290556,21.850833,AGS,OBSAG,"Observatorio, Ags.",20.9,NaN
11,2018,-102.465000,22.189167,AGS,P50ANIV,"Presa 50 Aniversario, Ags. SMN*",57.2,NaN
12,2018,-101.966667,21.916667,AGS,PALAG,"Palo Alto, Ags.",19.0,NaN
13,2018,-102.291944,22.162500,AGS,PBLAG,"Pabellón, Ags.",22.0,NaN
14,2018,-102.417222,22.141111,AGS,PECAG,"Calles, Ags.",50.0,NaN
15,2018,-102.133333,22.202778,AGS,PTOAG,"Puerto de la Concepción, Ags.",26.7,NaN
16,2018,-102.437500,22.235000,AGS,PTRAG,"Potrerillos, Ags.",52.8,NaN
17,2018,-102.108889,21.885000,AGS,SNVAG,"Sandovales, Ags.",8.0,NaN
18,2018,-102.127778,21.807778,AGS,TNJAG,"La Tinaja II, Ags.",10.0,NaN
19,2018,-102.067500,22.097778,AGS,VJZAG,"Villa Juárez, Ags.",16.9,NaN
20,2018,-114.730278,32.704722,BC,ALGODONESob,OBSERVATORIO DE ALGODONES SMN,1.4,NaN
21,2018,-116.908333,32.444722,BC,ALRBN,"Abelardo L. Rodríguez, B.C.",53.6,NaN
22,2018,-114.719167,29.727222,BC,CATAVINA,"Cataviña, B.C. SMN*",0.5,NaN
23,2018,-116.696944,32.479444,BC,CRRBN,"El Carrizo, B.C.",47.6,NaN
24,2018,-116.828333,32.468056,BC,EFLBN,"El Florido, B.C.",44.6,NaN
25,2018,-116.602500,31.890278,BC,ELZBN,"Emilio López Zamora, B.C.",24.0,NaN
26,2018,-115.931389,30.517222,BC,ENBBN,SAN QUINTIN (EJIDO NUEVO),7.6,NaN
27,2018,-115.150000,32.411111,BC,ENLBN,"Ejido Nuevo León, B.C.",0.0,NaN
28,2018,-116.302778,32.516389,BC,HNGBN,"El Hongo, B.C.",35.9,NaN
29,2018,-116.811111,32.101944,BC,LAMBN,"La Misión, B.C.",0.0,NaN
...,...,...,...,...,...,...,...,...
1191,2019,-102.890833,23.173889,ZAC,FREZC,"Fresnillo, Zac.",NaN,0.00
1192,2019,-103.093333,22.933333,ZAC,GJAZC,"General Joaquín Amaro, Zac.",NaN,0.00
1193,2019,-102.506667,22.746667,ZAC,GPEZC,"Guadalupe, Zac.",NaN,5.80
1194,2019,-102.460000,22.487500,ZAC,GRCZC,"Genaro Codina, Zac.",NaN,0.00
1195,2019,-103.114167,21.404722,ZAC,JCHZC,"Juchipila, Zac.",NaN,0.00
1196,2019,-103.001944,22.642778,ZAC,JERZC,"Jerez, Zac.",NaN,2.50
1197,2019,-102.566944,22.778889,ZAC,LBUZC,"La Bufa, Zac.",NaN,0.00
1198,2019,-103.603056,22.686944,ZAC,LFLZC,"La Florida, Zac.",NaN,0.00
1199,2019,-102.660556,22.996944,ZAC,LLBZC,"Llano Blanco, Zac.",NaN,0.00
1200,2019,-103.382778,22.845278,ZAC,LOBZC,"Manuel Felgueres, Zac.",NaN,2.00
1201,2019,-101.985556,22.264722,ZAC,LORZC,"Loreto, Zac.",NaN,6.10
1202,2019,-103.216944,23.180000,ZAC,LREZC,"Gobernador Leobardo Reynoso, Zac.",NaN,1.20
1203,2019,-103.363889,21.212500,ZAC,MORZC,"Mezquital del Oro, Zac.",NaN,0.00
1204,2019,-103.561667,22.306944,ZAC,MRSZC,"Monte Escobedo, Zac.",NaN,0.00
1205,2019,-102.845556,21.357500,ZAC,NCTZC,"Nochistlán, Zac.",NaN,0.00
1206,2019,-102.798056,22.347778,ZAC,PALZC,"Palomas, Zac.",NaN,0.00
1207,2019,-101.399167,22.117500,ZAC,PINZC,"Pino Suárez, Zac.",NaN,3.20
1208,2019,-102.903611,21.711111,ZAC,PMOZC,"Moraleños, Zac.",NaN,1.01
1209,2019,-103.025833,23.816944,ZAC,RGRZC,"Río Grande, Zac.",NaN,9.11
1210,2019,-102.884444,24.322222,ZAC,SFOZC,"San Francisco, Zac.",NaN,2.32
1211,2019,-103.506111,24.288611,ZAC,SGOZC,"Santiago, Zac.",NaN,0.40
1212,2019,-103.636667,23.638889,ZAC,SOMZC,"Sombrerete, Zac.",NaN,2.80
1213,2019,-103.495833,22.326667,ZAC,STEZC,"Santa Teresa (Independencia Nacional), Zac.",NaN,1.00
1214,2019,-103.108889,22.923611,ZAC,STRZC,"Santa Rosa, Zac.",NaN,4.21
1215,2019,-102.864167,22.120556,ZAC,TAYZC,"Ing. Julián Adame Alatorre, Zac.",NaN,0.00
1216,2019,-103.879722,23.471944,ZAC,TCHZC,"Chalchihuites, Zac.",NaN,4.00
1217,2019,-103.309444,21.773611,ZAC,TLLZC,"Tlaltenango, Zac.",NaN,0.02
1218,2019,-102.344167,23.288611,ZAC,VCOZC,"Villa de Cos, Zac.",NaN,0.00
1219,2019,-101.715833,22.347500,ZAC,VHGZC,"Villa Hidalgo, Zac.",NaN,4.51
1220,2019,-103.337500,21.588889,ZAC,VILZC,"José María Morelos, Zac.",NaN,0.00

Podemos hacerlo tambien con pd.concat

In [104]:
lluvias_2 = pd.concat([lluvias_2018, lluvias_2019], keys=['2018', '2019'],sort=False)[['LON', 'LAT', 'EDO', 'CLAVE_SIH', 'NOMBRE', 'ENE', 'MAY']]

In [118]:
lluvias_2[:'2018']

                  LON        LAT   EDO              CLAVE_SIH  \
2018 0    -102.309722  21.895000   AGS                  AGSAG
     1    -102.466944  22.188611   AGS                  ANVAG
     2    -102.712222  21.849167   AGS               CALVILLO
     3    -102.676944  21.997500   AGS                  CDRAG
     4    -102.197222  22.007222   AGS                  CHOAG
     5    -102.189167  21.826667   AGS                  CLVAG
     6    -102.000000  21.896389   AGS                  CNSAG
     7    -102.296667  22.362778   AGS                  CSOAG
     8    -102.788333  21.807500   AGS                  MNLAG
     9    -102.371667  21.780000   AGS                  NGRAG
     10   -102.290556  21.850833   AGS                  OBSAG
     11   -102.465000  22.189167   AGS                P50ANIV
     12   -101.966667  21.916667   AGS                  PALAG
     13   -102.291944  22.162500   AGS                  PBLAG
     14   -102.417222  22.141111   AGS                  PECAG
     15   -102.133333  22.202778   AGS                  PTOAG
     16   -102.437500  22.235000   AGS                  PTRAG
     17   -102.108889  21.885000   AGS                  SNVAG
     18   -102.127778  21.807778   AGS                  TNJAG
     19   -102.067500  22.097778   AGS                  VJZAG
     20   -114.730278  32.704722    BC            ALGODONESob
     21   -116.908333  32.444722    BC                  ALRBN
     22   -114.719167  29.727222    BC               CATAVINA
     23   -116.696944  32.479444    BC                  CRRBN
     24   -116.828333  32.468056    BC                  EFLBN
     25   -116.602500  31.890278    BC                  ELZBN
     26   -115.931389  30.517222    BC                  ENBBN
     27   -115.150000  32.411111    BC                  ENLBN
     28   -116.302778  32.516389    BC                  HNGBN
     29   -116.811111  32.101944    BC                  LAMBN
...               ...        ...   ...                    ...
     1854 -107.905278  27.221667  CHIH              URIQUECFE
     1855 -102.028889  19.380833  MICH                URUAPAN
     1856  -96.381389  17.925556   OAX               USILACFE
     1857 -100.084806  19.375583   MEX           VALLEDEBRAVO
     1858 -112.029833  26.872417   BCS          VALLEDEMULEGE
     1859  -99.213681  19.511038   MEX            VASOECRISTO
     1860 -100.950000  27.519444  COAH  VENUSTIANOCARRANZASMN
     1861  -96.111388  19.142500   VER               VERACRUZ
     1862 -106.505178  30.615644  CHIH           VILLAAHUMADA
     1863  -99.126603  19.286691    DF             VILLACOAPA
     1864  -99.488611  24.470556  TAMS              VILLAGRAN
     1865  -92.933333  17.983333   TAB           VILLAHERMOSA
     1866  -92.147306  15.090833  CHIS           VOLCANTACANA
     1867  -96.903889  19.511944   VER                 XALAPA
     1868  -97.681111  19.796389   PUE          XALCOMULCOCFE
     1869  -99.144611  19.332867    DF              XOTEPINGO
     1870  -93.328333  17.120833  CHIS             YAMONHOCFE
     1871  -99.286797  19.363737    DF                  YAQUI
     1872 -108.916667  28.366667   SON                 YECORA
     1873  -90.311097  19.013611  CAMP               YOHALTUM
     1874 -101.686694  22.900306   SLP                YOLIATL
     1875 -102.506111  22.746670   ZAC          ZACATECAS_EMA
     1876 -102.566389  22.778333   ZAC        ZACATECAS_ESIME
     1877  -99.207222  18.644167   MOR              ZACATEPEC
     1878  -98.672083  20.665056   HGO         ZACUALTIPANSMN
     1879  -98.842833  19.936722   HGO               ZAPOTLAN
     1880  -99.352933  19.295445   MEX                  ZARCO
     1881 -101.227500  18.060556   GRO           ZIHUAQUIOCFE
     1882 -101.554889  17.645056   GRO            ZIHUATANEJO
     1883  -99.390806  20.740222   HGO             ZIMAPANSMN

                                     NOMBRE    ENE  MAY
2018 0                 Aguascalientes, Ags.   25.8  NaN
     1          Cincuenta Aniversario, Ags.   58.6  NaN
     2                  Calvillo, Ags. SMN*   56.0  NaN
     3                    La Codorniz, Ags.   50.0  NaN
     4                   Cañada Honda, Ags.   17.2  NaN
     5                     Calvillito, Ags.   13.5  NaN
     6                      Los Conos, Ags.   51.5  NaN
     7                          Cosio, Ags.   35.5  NaN
     8                     Media Luna, Ags.   48.9  NaN
     9                     El Niagara, Ags.   25.4  NaN
     10                  Observatorio, Ags.   20.9  NaN
     11     Presa 50 Aniversario, Ags. SMN*   57.2  NaN
     12                     Palo Alto, Ags.   19.0  NaN
     13                      Pabellón, Ags.   22.0  NaN
     14                        Calles, Ags.   50.0  NaN
     15       Puerto de la Concepción, Ags.   26.7  NaN
     16                   Potrerillos, Ags.   52.8  NaN
     17                    Sandovales, Ags.    8.0  NaN
     18                  La Tinaja II, Ags.   10.0  NaN
     19                  Villa Juárez, Ags.   16.9  NaN
     20       OBSERVATORIO DE ALGODONES SMN    1.4  NaN
     21         Abelardo L. Rodríguez, B.C.   53.6  NaN
     22                 Cataviña, B.C. SMN*    0.5  NaN
     23                    El Carrizo, B.C.   47.6  NaN
     24                    El Florido, B.C.   44.6  NaN
     25           Emilio López Zamora, B.C.   24.0  NaN
     26           SAN QUINTIN (EJIDO NUEVO)    7.6  NaN
     27              Ejido Nuevo León, B.C.    0.0  NaN
     28                      El Hongo, B.C.   35.9  NaN
     29                     La Misión, B.C.    0.0  NaN
...                                     ...    ...  ...
     1854                            Urique    0.0  NaN
     1855                           Uruapan   24.3  NaN
     1856  San Juan Bautista Valle Nacional    0.5  NaN
     1857                  Villa de Allende    5.8  NaN
     1858                            Mulegé    0.0  NaN
     1859               Tlalnepantla de Baz   32.2  NaN
     1860                            Juárez    0.2  NaN
     1861                      Boca del Río   23.2  NaN
     1862                           Ahumada    0.2  NaN
     1863                           Tlalpan    3.6  NaN
     1864                         Villagrán   12.4  NaN
     1865                            Centro  403.2  NaN
     1866                        Cacahoatán   15.8  NaN
     1867                            Xalapa   43.8  NaN
     1868                            Zautla    3.8  NaN
     1869                          Coyoacán   10.2  NaN
     1870                          Tecpatán  219.4  NaN
     1871                 Cuajimalpa de MOR    8.1  NaN
     1872                            Yécora    0.0  NaN
     1873                         Champotón   69.6  NaN
     1874                    Villa de Ramos    3.6  NaN
     1875                         Guadalupe   42.5  NaN
     1876                         Zacatecas   21.4  NaN
     1877                         Zacatepec    0.0  NaN
     1878            Zacualtipán de Ángeles   94.4  NaN
     1879                Zapotlán de Juárez    4.4  NaN
     1880                         Ocoyoacac   20.4  NaN
     1881                 Coyuca de Catalán    0.4  NaN
     1882             Zihuatanejo de Azueta    2.2  NaN
     1883                           Zimapán    9.8  NaN

[1884 rows x 7 columns]

In [129]:
display(lluvias_2[:'2018'].head(),lluvias_2['2019':].head())

               LON        LAT  EDO CLAVE_SIH                       NOMBRE  \
2018 0 -102.309722  21.895000  AGS     AGSAG         Aguascalientes, Ags.
     1 -102.466944  22.188611  AGS     ANVAG  Cincuenta Aniversario, Ags.
     2 -102.712222  21.849167  AGS  CALVILLO          Calvillo, Ags. SMN*
     3 -102.676944  21.997500  AGS     CDRAG            La Codorniz, Ags.
     4 -102.197222  22.007222  AGS     CHOAG           Cañada Honda, Ags.

         ENE  MAY
2018 0  25.8  NaN
     1  58.6  NaN
     2  56.0  NaN
     3  50.0  NaN
     4  17.2  NaN

               LON        LAT  EDO CLAVE_SIH                       NOMBRE  \
2019 0 -102.309722  21.895000  AGS     AGSAG         Aguascalientes, Ags.
     1 -102.466944  22.188611  AGS     ANVAG  Cincuenta Aniversario, Ags.
     2 -102.184167  21.738611  AGS     BRTAG            San Bartolo, Ags.
     3 -102.712222  21.849167  AGS  CALVILLO          Calvillo, Ags. SMN*
     4 -102.676944  21.997500  AGS     CDRAG            La Codorniz, Ags.

        ENE   MAY
2019 0  NaN  2.12
     1  NaN  4.20
     2  NaN  0.00
     3  NaN  5.32
     4  NaN  0.00

# Tarea 4 
Busca dos paginas en internet donde la base de datos no esté disponible para descargarse sino que este en forma de tabla. Descargalas como en el ejemplo de clase.

# VIH/SIDA 
Esta entrada proporciona una estimación de todas las personas (adultos y niños) que están vivas al final del año con infección por VIH, hayan desarrollado o no síntomas de SIDA.

In [156]:
url = 'https://www.indexmundi.com/map/?v=35&l=es'
html = requests.get(url).content
VIH = pd.read_html(html)[2]

In [162]:
VIH.head()

  Country  Birth rate (births/1,000 population)  Year
0  Angola                                    44  2017
1   Niger                                    44  2017
2    Mali                                    44  2017
3  Uganda                                    43  2017
4  Zambia                                    42  2017

# Birth rate
This entry gives the average annual number of births during a year per 1,000 persons in the population at midyear; also known as crude birth rate. The birth rate is usually the dominant factor in determining the rate of population growth. It depends on both the level of fertility and the age structure of the population.

In [159]:
url = 'https://www.indexmundi.com/map/?t=0&v=25&r=xx&l=en'
html = requests.get(url).content
Birth_rate = pd.read_html(html)[2]

In [161]:
Birth_rate.head()

  Country  Birth rate (births/1,000 population)  Year
0  Angola                                    44  2017
1   Niger                                    44  2017
2    Mali                                    44  2017
3  Uganda                                    43  2017
4  Zambia                                    42  2017

In [163]:
url = 'http://fisica.ugto.mx/index.php/oferta-educativa-dci/oe-licenciatura/licenciatura-fisica-2016'
html = requests.get(url).content
Fisica = pd.read_html(html)

In [170]:
Creditos = Fisica[2]
display(Creditos)

,Distribución de créditos de la Licenciatura en Física,Distribución de créditos de la Licenciatura en Física.1
0,Créditos Obligatorios,163
1,Créditos del Área General,Mínimo 28
2,Créditos Optativos Disciplinares,Mínimo 35
3,Total mínimo,226

In [181]:
Plan = Fisica[3]
Plan

,0,1,2,3,4,5,6,7
0,Primera inscripción,Segunda inscripción,Tercera inscripción,Cuarta inscripción,Quinta inscripción,Sexta inscripción,Séptima inscripción,Octava inscripción
1,Matemáticas Superiores,Álgebra Lineal,Cálculo de varias variables,Análisis Vectorial,Ecuaciones Diferenciales Parciales,Mecánica Cuántica,Óptica,Optativa
2,Programación Básica,Cálculo Diferencial,Ecuaciones Diferenciales Ordinarias,Variable Compleja,Electromagnetismo,Mecánica Estadística,Taller de Investigación,Optativa
3,Física General,Cálculo Integral,"Fluidos, Ondas y Temperatura",Probabilidad y Estadística,Mecánica Analítica,Funciones Especiales,Laboratorio Avanzado,Optativa
4,Química General,Mecánica Clásica,Métodos Numéricos,Electricidad y Magnetismo,Termodinámica,Física Relativista,Temas Selectos de Física,Créditos del Área General
5,Desarrollo histórico de la Física Moderna,Herramientas informáticas y Gestión de la info...,Optativa,Optativa,Física Cuántica,Optativa,Optativa,NaN
6,Créditos del Área General,Créditos del Área General,Créditos del Área General,Créditos del Área General,Créditos del Área General,Créditos del Área General,Créditos del Área General,NaN

In [197]:
url = 'https://intraug.ugto.mx/SIIUG#div_BancoDatos_SSU'
html = requests.get(url).content
yo = pd.read_html(html)

ValueError: No tables found

In [194]:
yo

[                       UbicaciÃ³n                               Persona  \
 0  CNMS (Todas las Preparatorias)       MÃ³nica Alejandra Gracia OrtÃ­z
 1      Licenciaturas y Posgrados:            Licenciaturas y Posgrados:
 2            Celaya - Salvatierra        Lic. Gabino Saavedra Maldonado
 3                      Guanajuato  Lic. Juan Bardo Rodriguez de la Vega
 4            Irapuato - Salamanca    Mtro. Heriberto GutiÃ©rrez MartÃ­n
 5                           LeÃ³n           Lic. VerÃ³nica Meza Bedolla

                                             Contacto
 0                  Ext. 3910 y 3925  graciam@ugto.mx
 1                         Licenciaturas y Posgrados:
 2  Conmutador: 461 598 59 22  ExtensiÃ³n 1609  ca...
 3  Conmutador: 01473 735 29 00  ExtensiÃ³n 2915  ...
 4  Conmutador: 01464 647 99 40  ExtensiÃ³n 2327  ...
 5  Conmutador: 01477 267 49 00  ExtensiÃ³n 4864  ...  ]