# Tarea 3
Crear una sola base de datos que tenga todas las tablas de los archivos anteriores (usando las herramientas aprendidas en 2). Haz una para la temperatura, y otra para las lluvias.

In [287]:
import numpy as np
import math as mt
import matplotlib.pyplot as plt
import pandas as pd
import requests
import os
import lxml.html as lh

In [288]:
#Cargamos los Datos de los archivos
path_ll_18 = '/home/echeveste/Mis_trabajos/analisis_datos/da2019-Oscar2401/Semana2/Tareas/dato_temperaturas_lluvia/201801010000Lluv.csv'
path_Mx_18 = '/home/echeveste/Mis_trabajos/analisis_datos/da2019-Oscar2401/Semana2/Tareas/dato_temperaturas_lluvia/201801010000TMax.csv'
path_Mm_18 = '/home/echeveste/Mis_trabajos/analisis_datos/da2019-Oscar2401/Semana2/Tareas/dato_temperaturas_lluvia/201801010000TMin.csv'
path_Md_18 = '/home/echeveste/Mis_trabajos/analisis_datos/da2019-Oscar2401/Semana2/Tareas/dato_temperaturas_lluvia/201801010000TMed.csv'
path_ll_19 = '/home/echeveste/Mis_trabajos/analisis_datos/da2019-Oscar2401/Semana2/Tareas/dato_temperaturas_lluvia/201905010000Lluv.csv'
path_Mx_19 = '/home/echeveste/Mis_trabajos/analisis_datos/da2019-Oscar2401/Semana2/Tareas/dato_temperaturas_lluvia/201901010000TMax.csv'
path_Mm_19 = '/home/echeveste/Mis_trabajos/analisis_datos/da2019-Oscar2401/Semana2/Tareas/dato_temperaturas_lluvia/201901010000TMin.csv'
path_Md_19 = '/home/echeveste/Mis_trabajos/analisis_datos/da2019-Oscar2401/Semana2/Tareas/dato_temperaturas_lluvia/201901010000TMed.csv'

In [289]:
lluvias_2018 = pd.read_csv(path_ll_18,encoding='latin-1')
Maxima_2018 = pd.read_csv(path_Mx_18,encoding='latin-1')
Minima_2018 = pd.read_csv(path_Mm_18,encoding='latin-1')
Media_2018 = pd.read_csv(path_Md_18,encoding='latin-1')
lluvias_2019 = pd.read_csv(path_ll_19,encoding='latin-1')
Maxima_2019 = pd.read_csv(path_Mx_19,encoding='latin-1')
Minima_2019 = pd.read_csv(path_Mm_19,encoding='latin-1')
Media_2019 = pd.read_csv(path_Md_19,encoding='latin-1')

In [290]:
lluvias_2018 = lluvias_2018.rename(columns={'ESTADO' : 'EDO'})
display(lluvias_2018.head(),lluvias_2019.head())

          LON        LAT  EDO CLAVE_SIH                       NOMBRE   ENE
0 -102.309722  21.895000  AGS     AGSAG         Aguascalientes, Ags.  25.8
1 -102.466944  22.188611  AGS     ANVAG  Cincuenta Aniversario, Ags.  58.6
2 -102.712222  21.849167  AGS  CALVILLO          Calvillo, Ags. SMN*  56.0
3 -102.676944  21.997500  AGS     CDRAG            La Codorniz, Ags.  50.0
4 -102.197222  22.007222  AGS     CHOAG           Cañada Honda, Ags.  17.2

          LON        LAT  EDO CLAVE_SIH                       NOMBRE   MAY
0 -102.309722  21.895000  AGS     AGSAG         Aguascalientes, Ags.  2.12
1 -102.466944  22.188611  AGS     ANVAG  Cincuenta Aniversario, Ags.  4.20
2 -102.184167  21.738611  AGS     BRTAG            San Bartolo, Ags.  0.00
3 -102.712222  21.849167  AGS  CALVILLO          Calvillo, Ags. SMN*  5.32
4 -102.676944  21.997500  AGS     CDRAG            La Codorniz, Ags.  0.00

In [291]:
lluvias_2018['AÑO'] = pd.Series(2018*np.ones_like(lluvias_2018['EDO']))
lluvias_2019['AÑO'] = pd.Series(2019*np.ones_like(lluvias_2019['EDO']))

In [292]:
lluvias_1 = pd.concat([lluvias_2018,lluvias_2019 ],sort=False)[['AÑO','LON', 'LAT', 'EDO', 'CLAVE_SIH', 'NOMBRE', 'ENE', 'MAY']]

In [293]:
lluvias_1

,AÑO,LON,LAT,EDO,CLAVE_SIH,NOMBRE,ENE,MAY
0,2018,-102.309722,21.895000,AGS,AGSAG,"Aguascalientes, Ags.",25.8,NaN
1,2018,-102.466944,22.188611,AGS,ANVAG,"Cincuenta Aniversario, Ags.",58.6,NaN
2,2018,-102.712222,21.849167,AGS,CALVILLO,"Calvillo, Ags. SMN*",56.0,NaN
3,2018,-102.676944,21.997500,AGS,CDRAG,"La Codorniz, Ags.",50.0,NaN
4,2018,-102.197222,22.007222,AGS,CHOAG,"Cañada Honda, Ags.",17.2,NaN
5,2018,-102.189167,21.826667,AGS,CLVAG,"Calvillito, Ags.",13.5,NaN
6,2018,-102.000000,21.896389,AGS,CNSAG,"Los Conos, Ags.",51.5,NaN
7,2018,-102.296667,22.362778,AGS,CSOAG,"Cosio, Ags.",35.5,NaN
8,2018,-102.788333,21.807500,AGS,MNLAG,"Media Luna, Ags.",48.9,NaN
9,2018,-102.371667,21.780000,AGS,NGRAG,"El Niagara, Ags.",25.4,NaN
10,2018,-102.290556,21.850833,AGS,OBSAG,"Observatorio, Ags.",20.9,NaN
11,2018,-102.465000,22.189167,AGS,P50ANIV,"Presa 50 Aniversario, Ags. SMN*",57.2,NaN
12,2018,-101.966667,21.916667,AGS,PALAG,"Palo Alto, Ags.",19.0,NaN
13,2018,-102.291944,22.162500,AGS,PBLAG,"Pabellón, Ags.",22.0,NaN
14,2018,-102.417222,22.141111,AGS,PECAG,"Calles, Ags.",50.0,NaN
15,2018,-102.133333,22.202778,AGS,PTOAG,"Puerto de la Concepción, Ags.",26.7,NaN
16,2018,-102.437500,22.235000,AGS,PTRAG,"Potrerillos, Ags.",52.8,NaN
17,2018,-102.108889,21.885000,AGS,SNVAG,"Sandovales, Ags.",8.0,NaN
18,2018,-102.127778,21.807778,AGS,TNJAG,"La Tinaja II, Ags.",10.0,NaN
19,2018,-102.067500,22.097778,AGS,VJZAG,"Villa Juárez, Ags.",16.9,NaN
20,2018,-114.730278,32.704722,BC,ALGODONESob,OBSERVATORIO DE ALGODONES SMN,1.4,NaN
21,2018,-116.908333,32.444722,BC,ALRBN,"Abelardo L. Rodríguez, B.C.",53.6,NaN
22,2018,-114.719167,29.727222,BC,CATAVINA,"Cataviña, B.C. SMN*",0.5,NaN
23,2018,-116.696944,32.479444,BC,CRRBN,"El Carrizo, B.C.",47.6,NaN
24,2018,-116.828333,32.468056,BC,EFLBN,"El Florido, B.C.",44.6,NaN
25,2018,-116.602500,31.890278,BC,ELZBN,"Emilio López Zamora, B.C.",24.0,NaN
26,2018,-115.931389,30.517222,BC,ENBBN,SAN QUINTIN (EJIDO NUEVO),7.6,NaN
27,2018,-115.150000,32.411111,BC,ENLBN,"Ejido Nuevo León, B.C.",0.0,NaN
28,2018,-116.302778,32.516389,BC,HNGBN,"El Hongo, B.C.",35.9,NaN
29,2018,-116.811111,32.101944,BC,LAMBN,"La Misión, B.C.",0.0,NaN
...,...,...,...,...,...,...,...,...
1191,2019,-102.890833,23.173889,ZAC,FREZC,"Fresnillo, Zac.",NaN,0.00
1192,2019,-103.093333,22.933333,ZAC,GJAZC,"General Joaquín Amaro, Zac.",NaN,0.00
1193,2019,-102.506667,22.746667,ZAC,GPEZC,"Guadalupe, Zac.",NaN,5.80
1194,2019,-102.460000,22.487500,ZAC,GRCZC,"Genaro Codina, Zac.",NaN,0.00
1195,2019,-103.114167,21.404722,ZAC,JCHZC,"Juchipila, Zac.",NaN,0.00
1196,2019,-103.001944,22.642778,ZAC,JERZC,"Jerez, Zac.",NaN,2.50
1197,2019,-102.566944,22.778889,ZAC,LBUZC,"La Bufa, Zac.",NaN,0.00
1198,2019,-103.603056,22.686944,ZAC,LFLZC,"La Florida, Zac.",NaN,0.00
1199,2019,-102.660556,22.996944,ZAC,LLBZC,"Llano Blanco, Zac.",NaN,0.00
1200,2019,-103.382778,22.845278,ZAC,LOBZC,"Manuel Felgueres, Zac.",NaN,2.00
1201,2019,-101.985556,22.264722,ZAC,LORZC,"Loreto, Zac.",NaN,6.10
1202,2019,-103.216944,23.180000,ZAC,LREZC,"Gobernador Leobardo Reynoso, Zac.",NaN,1.20
1203,2019,-103.363889,21.212500,ZAC,MORZC,"Mezquital del Oro, Zac.",NaN,0.00
1204,2019,-103.561667,22.306944,ZAC,MRSZC,"Monte Escobedo, Zac.",NaN,0.00
1205,2019,-102.845556,21.357500,ZAC,NCTZC,"Nochistlán, Zac.",NaN,0.00
1206,2019,-102.798056,22.347778,ZAC,PALZC,"Palomas, Zac.",NaN,0.00
1207,2019,-101.399167,22.117500,ZAC,PINZC,"Pino Suárez, Zac.",NaN,3.20
1208,2019,-102.903611,21.711111,ZAC,PMOZC,"Moraleños, Zac.",NaN,1.01
1209,2019,-103.025833,23.816944,ZAC,RGRZC,"Río Grande, Zac.",NaN,9.11
1210,2019,-102.884444,24.322222,ZAC,SFOZC,"San Francisco, Zac.",NaN,2.32
1211,2019,-103.506111,24.288611,ZAC,SGOZC,"Santiago, Zac.",NaN,0.40
1212,2019,-103.636667,23.638889,ZAC,SOMZC,"Sombrerete, Zac.",NaN,2.80
1213,2019,-103.495833,22.326667,ZAC,STEZC,"Santa Teresa (Independencia Nacional), Zac.",NaN,1.00
1214,2019,-103.108889,22.923611,ZAC,STRZC,"Santa Rosa, Zac.",NaN,4.21
1215,2019,-102.864167,22.120556,ZAC,TAYZC,"Ing. Julián Adame Alatorre, Zac.",NaN,0.00
1216,2019,-103.879722,23.471944,ZAC,TCHZC,"Chalchihuites, Zac.",NaN,4.00
1217,2019,-103.309444,21.773611,ZAC,TLLZC,"Tlaltenango, Zac.",NaN,0.02
1218,2019,-102.344167,23.288611,ZAC,VCOZC,"Villa de Cos, Zac.",NaN,0.00
1219,2019,-101.715833,22.347500,ZAC,VHGZC,"Villa Hidalgo, Zac.",NaN,4.51
1220,2019,-103.337500,21.588889,ZAC,VILZC,"José María Morelos, Zac.",NaN,0.00

Podemos hacerlo tambien con pd.concat

In [294]:
lluvias_2 = pd.concat([lluvias_2018, lluvias_2019], keys=['2018', '2019'],sort=False)[['LON', 'LAT', 'EDO', 'CLAVE_SIH', 'NOMBRE', 'ENE', 'MAY']]

In [304]:
lluvias_2

             Lon    Lat    Edo         Clave  \
2018 0   -101.51  20.43    GTO         ABSGJ
     1    -98.38  24.06  TAMPS         ABSTP
     2   -116.90  32.44     BC         ALRBN
     3    -97.97  20.17    PUE         ACJPB
     4    -92.80  16.55   CHIS         ACACP
     5   -100.71  20.03    GTO         ACNGJ
     6    -99.75  16.76    GRO         76805
     7    -99.90  16.84    GRO         ACAGR
     8    -96.84  19.70    VER         ACAVC
     9   -103.23  22.33    ZAC         ACHZC
     10  -110.21  30.00    SON         ACNSO
     11   -98.94  20.26    HGO         ACTHD
     12   -96.58  19.49    VER         ACTVC
     13  -108.70  25.70    SIN         ARCSI
     14   -99.50  17.50    GRO         AERGR
     15  -100.93  25.55   COAH         ARACL
     16  -104.48  26.23    DGO         APRDR
     17  -101.62  20.49    GTO         ATBGJ
     18  -102.29  21.85    AGS         76571
     19  -102.30  21.89    AGS         AGSAG
     20  -104.07  25.26    DGO         AM2DR
     21   -98.14  20.03    PUE         AHUPB
     22   -97.41  19.45    PUE         ACHPB
     23  -100.84  28.33   COAH         ADLCL
     24  -111.83  30.71    SON         76113
     25  -111.73  30.71    SON         ALTSO
     26   -97.23  19.76    VER         ALTVC
     27  -107.46  25.03    SIN         AWSSI
     28   -92.75  16.44   CHIS         ANGCP
     29   -97.84  20.41    PUE         APAPB
...          ...    ...    ...           ...
2019 605  -97.40  20.12    PUE         RNAPB
     606 -107.16  24.81    SIN         SN2SI
     607 -107.91  25.86    SIN         GD2SI
     608 -108.32  26.08    SIN         GB2SI
     609 -108.32  26.70    SIN         76311
     610 -109.37  28.98    SON  PELIASCALLES
     611  -99.19  23.73  TAMPS         CVTTP
     612  -99.12  24.08  TAMPS    BARRETALII
     613  -98.69  25.12  TAMPS     CANDIDOAG
     614  -89.68  20.65    YUC         ABAYC
     615  -90.38  20.86    YUC         CELYC
     616  -89.44  21.11    YUC         MOCYC
     617 -103.50  22.33    ZAC         STEZC
     618  -92.27  15.33   CHIS    MOTOZINTLA
     619  -99.20  19.50     DF         CCH A
     620  -94.16  17.57    VER         TMOVC
     621  -92.32  15.56   CHIS      SILTEPEC
     622  -99.15  22.99  TAMPS         AHLTP
     623  -96.65  19.32    VER         CRRVC
     624 -107.26  28.77   CHIH         BACCH
     625  -99.12  19.27     DF         ENP 1
     626 -103.73  22.40    JAL         BCSJL
     627  -99.47  18.80    MEX         CHDMX
     628  -99.73  18.93    MEX         PDZMX
     629  -99.65  19.30    MEX         RECMX
     630  -99.24  19.47    MEX         CCH N
     631  -99.80  19.63    MEX         SMLMX
     632  -95.93  17.15    OAX         ZACOX
     633  -95.52  18.63    VER         NLTVC
     634  -89.50  21.08    YUC         CONYC

                                                       Est       Tmed
2018 0                                             ABASOLO  16.200000
     1                                             ABASOLO  15.000000
     2                               ABELARDO L. RODRIGUEZ  16.700000
     3                 ACAJETE                           *  12.300000
     4                                               ACALA  21.200000
     5                                            ACAMBARO  15.000000
     6                                            ACAPULCO  27.200000
     7                                            ACAPULCO  25.400000
     8                                             ACATLAN  12.800000
     9                                             ACHIMEC  12.800000
     10                                            ACONCHI  14.800000
     11                                            ACTOPAN  13.300000
     12                                            ACTOPAN  20.000000
     13                               ADOLFO RUIZ CORTINEZ  20.100000
     14                                         AEROPUERTO  21.300000
     15                         AEROPUERTO DE RAMOS ARIZPE  10.000000
     16                                        AGUA PUERCA  10.500000
     17                                         AGUA TIBIA  13.500000
     18                                     AGUASCALIENTES  13.200000
     19                                     AGUASCALIENTES  14.000000
     20                              AGUSTIN MELGAR (EHCA)  12.500000
     21                                        AHUAZOTEPEC   7.500000
     22                                         ALCHICHICA   9.400000
     23                                            ALLENDE  10.700000
     24                                              ALTAR  16.500000
     25                                              ALTAR  16.800000
     26                                          ALTOTONGA   9.200000
     27                                       ANDREW WEISS  20.200000
     28                                          ANGOSTURA  21.700000
     29                                        APAPANTILLA  18.600000
...                                                    ...        ...
2019 605                                 Rancho Nuevo Pue.  19.931034
     606                        Sanalona hidrométrica Sin.  19.451613
     607  Bacurato hidrométrica de Gustavo Diaz Ordáz Sin.  20.338710
     608                      El Sabinal hidrométrica Sin.  19.870968
     609                                             CHOIX  19.319355
     610             Presa Plutarco Elías Calles Son. SGT*  17.080000
     611                            Ciudad Victoria Tamps.  17.018519
     612                          Barretal Dos Tamps. SGT*  16.151786
     613                       Cándido Aguilar Tamps. SGT*  16.050000
     614                                        Abalá Yuc.  19.508065
     615                                Celestún Yuc. SMN*  23.337931
     616                                      Mocochá Yuc.  21.467742
     617                                 Santa Teresa Zac.  13.669355
     618                             Motozintla Chis. SGT*  16.294828
     619                                  CCH Azcapotzalco  15.079032
     620                                Tierra Morada Ver.  22.241071
     621                               Siltepec Chis. SGT*  20.737500
     622                                  Ahualulco Tamps.  19.508621
     623                                     Carrizal Ver.  21.975806
     624                                   Bachíniva Chih.   7.629032
     625                                    Gabino Barreda  15.000000
     626                                        Bocas Jal.  14.838710
     627                              Colonia Hidalgo Mex.  22.967742
     628                                Porfirio Díaz Méx.  13.532258
     629                                     Rectoría Méx.  12.388710
     630                                     CCH Naucalpan  15.232258
     631                        Santa María del Llano Méx.  11.161290
     632                                    Zacatepec Oax.  16.697917
     633                     Naranjal Lerdo de Tejada Ver.  22.269231
     634                                       Conkal Yuc.  20.870968

[1734 rows x 6 columns]

In [295]:
#visualizamos
display(lluvias_2[:'2018'].head(),lluvias_2['2019':].head())

               LON        LAT  EDO CLAVE_SIH                       NOMBRE  \
2018 0 -102.309722  21.895000  AGS     AGSAG         Aguascalientes, Ags.
     1 -102.466944  22.188611  AGS     ANVAG  Cincuenta Aniversario, Ags.
     2 -102.712222  21.849167  AGS  CALVILLO          Calvillo, Ags. SMN*
     3 -102.676944  21.997500  AGS     CDRAG            La Codorniz, Ags.
     4 -102.197222  22.007222  AGS     CHOAG           Cañada Honda, Ags.

         ENE  MAY
2018 0  25.8  NaN
     1  58.6  NaN
     2  56.0  NaN
     3  50.0  NaN
     4  17.2  NaN

               LON        LAT  EDO CLAVE_SIH                       NOMBRE  \
2019 0 -102.309722  21.895000  AGS     AGSAG         Aguascalientes, Ags.
     1 -102.466944  22.188611  AGS     ANVAG  Cincuenta Aniversario, Ags.
     2 -102.184167  21.738611  AGS     BRTAG            San Bartolo, Ags.
     3 -102.712222  21.849167  AGS  CALVILLO          Calvillo, Ags. SMN*
     4 -102.676944  21.997500  AGS     CDRAG            La Codorniz, Ags.

        ENE   MAY
2019 0  NaN  2.12
     1  NaN  4.20
     2  NaN  0.00
     3  NaN  5.32
     4  NaN  0.00

Hacemos lo mismo para la temperatura

In [298]:
print(Media_2018.keys())
print(Media_2019.keys())

Index(['Lon', 'Lat', 'Clave', 'Edo', 'Est', 'Tmed'], dtype='object')
Index(['Lon', 'Lat', 'Clave', 'Edo', 'Est', 'Tmed'], dtype='object')

In [300]:
T_medi = pd.concat([Media_2018, Media_2019], keys=['2018', '2019'],sort=False)[['Lon', 'Lat', 'Edo', 'Clave', 'Est', 'Tmed']]

In [303]:
T_medi

             Lon    Lat    Edo         Clave  \
2018 0   -101.51  20.43    GTO         ABSGJ
     1    -98.38  24.06  TAMPS         ABSTP
     2   -116.90  32.44     BC         ALRBN
     3    -97.97  20.17    PUE         ACJPB
     4    -92.80  16.55   CHIS         ACACP
     5   -100.71  20.03    GTO         ACNGJ
     6    -99.75  16.76    GRO         76805
     7    -99.90  16.84    GRO         ACAGR
     8    -96.84  19.70    VER         ACAVC
     9   -103.23  22.33    ZAC         ACHZC
     10  -110.21  30.00    SON         ACNSO
     11   -98.94  20.26    HGO         ACTHD
     12   -96.58  19.49    VER         ACTVC
     13  -108.70  25.70    SIN         ARCSI
     14   -99.50  17.50    GRO         AERGR
     15  -100.93  25.55   COAH         ARACL
     16  -104.48  26.23    DGO         APRDR
     17  -101.62  20.49    GTO         ATBGJ
     18  -102.29  21.85    AGS         76571
     19  -102.30  21.89    AGS         AGSAG
     20  -104.07  25.26    DGO         AM2DR
     21   -98.14  20.03    PUE         AHUPB
     22   -97.41  19.45    PUE         ACHPB
     23  -100.84  28.33   COAH         ADLCL
     24  -111.83  30.71    SON         76113
     25  -111.73  30.71    SON         ALTSO
     26   -97.23  19.76    VER         ALTVC
     27  -107.46  25.03    SIN         AWSSI
     28   -92.75  16.44   CHIS         ANGCP
     29   -97.84  20.41    PUE         APAPB
...          ...    ...    ...           ...
2019 605  -97.40  20.12    PUE         RNAPB
     606 -107.16  24.81    SIN         SN2SI
     607 -107.91  25.86    SIN         GD2SI
     608 -108.32  26.08    SIN         GB2SI
     609 -108.32  26.70    SIN         76311
     610 -109.37  28.98    SON  PELIASCALLES
     611  -99.19  23.73  TAMPS         CVTTP
     612  -99.12  24.08  TAMPS    BARRETALII
     613  -98.69  25.12  TAMPS     CANDIDOAG
     614  -89.68  20.65    YUC         ABAYC
     615  -90.38  20.86    YUC         CELYC
     616  -89.44  21.11    YUC         MOCYC
     617 -103.50  22.33    ZAC         STEZC
     618  -92.27  15.33   CHIS    MOTOZINTLA
     619  -99.20  19.50     DF         CCH A
     620  -94.16  17.57    VER         TMOVC
     621  -92.32  15.56   CHIS      SILTEPEC
     622  -99.15  22.99  TAMPS         AHLTP
     623  -96.65  19.32    VER         CRRVC
     624 -107.26  28.77   CHIH         BACCH
     625  -99.12  19.27     DF         ENP 1
     626 -103.73  22.40    JAL         BCSJL
     627  -99.47  18.80    MEX         CHDMX
     628  -99.73  18.93    MEX         PDZMX
     629  -99.65  19.30    MEX         RECMX
     630  -99.24  19.47    MEX         CCH N
     631  -99.80  19.63    MEX         SMLMX
     632  -95.93  17.15    OAX         ZACOX
     633  -95.52  18.63    VER         NLTVC
     634  -89.50  21.08    YUC         CONYC

                                                       Est       Tmed
2018 0                                             ABASOLO  16.200000
     1                                             ABASOLO  15.000000
     2                               ABELARDO L. RODRIGUEZ  16.700000
     3                 ACAJETE                           *  12.300000
     4                                               ACALA  21.200000
     5                                            ACAMBARO  15.000000
     6                                            ACAPULCO  27.200000
     7                                            ACAPULCO  25.400000
     8                                             ACATLAN  12.800000
     9                                             ACHIMEC  12.800000
     10                                            ACONCHI  14.800000
     11                                            ACTOPAN  13.300000
     12                                            ACTOPAN  20.000000
     13                               ADOLFO RUIZ CORTINEZ  20.100000
     14                                         AEROPUERTO  21.300000
     15                         AEROPUERTO DE RAMOS ARIZPE  10.000000
     16                                        AGUA PUERCA  10.500000
     17                                         AGUA TIBIA  13.500000
     18                                     AGUASCALIENTES  13.200000
     19                                     AGUASCALIENTES  14.000000
     20                              AGUSTIN MELGAR (EHCA)  12.500000
     21                                        AHUAZOTEPEC   7.500000
     22                                         ALCHICHICA   9.400000
     23                                            ALLENDE  10.700000
     24                                              ALTAR  16.500000
     25                                              ALTAR  16.800000
     26                                          ALTOTONGA   9.200000
     27                                       ANDREW WEISS  20.200000
     28                                          ANGOSTURA  21.700000
     29                                        APAPANTILLA  18.600000
...                                                    ...        ...
2019 605                                 Rancho Nuevo Pue.  19.931034
     606                        Sanalona hidrométrica Sin.  19.451613
     607  Bacurato hidrométrica de Gustavo Diaz Ordáz Sin.  20.338710
     608                      El Sabinal hidrométrica Sin.  19.870968
     609                                             CHOIX  19.319355
     610             Presa Plutarco Elías Calles Son. SGT*  17.080000
     611                            Ciudad Victoria Tamps.  17.018519
     612                          Barretal Dos Tamps. SGT*  16.151786
     613                       Cándido Aguilar Tamps. SGT*  16.050000
     614                                        Abalá Yuc.  19.508065
     615                                Celestún Yuc. SMN*  23.337931
     616                                      Mocochá Yuc.  21.467742
     617                                 Santa Teresa Zac.  13.669355
     618                             Motozintla Chis. SGT*  16.294828
     619                                  CCH Azcapotzalco  15.079032
     620                                Tierra Morada Ver.  22.241071
     621                               Siltepec Chis. SGT*  20.737500
     622                                  Ahualulco Tamps.  19.508621
     623                                     Carrizal Ver.  21.975806
     624                                   Bachíniva Chih.   7.629032
     625                                    Gabino Barreda  15.000000
     626                                        Bocas Jal.  14.838710
     627                              Colonia Hidalgo Mex.  22.967742
     628                                Porfirio Díaz Méx.  13.532258
     629                                     Rectoría Méx.  12.388710
     630                                     CCH Naucalpan  15.232258
     631                        Santa María del Llano Méx.  11.161290
     632                                    Zacatepec Oax.  16.697917
     633                     Naranjal Lerdo de Tejada Ver.  22.269231
     634                                       Conkal Yuc.  20.870968

[1734 rows x 6 columns]

In [302]:
#visualizamos
display(T_medi[:'2018'].head(),T_medi['2019':].head())

           Lon    Lat    Edo  Clave                                  Est  Tmed
2018 0 -101.51  20.43    GTO  ABSGJ                              ABASOLO  16.2
     1  -98.38  24.06  TAMPS  ABSTP                              ABASOLO  15.0
     2 -116.90  32.44     BC  ALRBN                ABELARDO L. RODRIGUEZ  16.7
     3  -97.97  20.17    PUE  ACJPB  ACAJETE                           *  12.3
     4  -92.80  16.55   CHIS  ACACP                                ACALA  21.2

           Lon    Lat   Edo  Clave               Est       Tmed
2019 0  -99.75  16.76   GRO  76805          ACAPULCO  27.441935
     1 -111.83  30.71   SON  76113             ALTAR  13.462069
     2  -93.90  16.24  CHIS  76840           ARRIAGA  28.088710
     3  -90.50  19.83  CAMP  76695          CAMPECHE  23.374074
     4 -111.65  25.01   BCS  76402  CD. CONSTITUCIÓN  17.987097

# Tarea 4 
Busca dos paginas en internet donde la base de datos no esté disponible para descargarse sino que este en forma de tabla. Descargalas como en el ejemplo de clase.

# VIH/SIDA 
Esta entrada proporciona una estimación de todas las personas (adultos y niños) que están vivas al final del año con infección por VIH, hayan desarrollado o no síntomas de SIDA.

In [156]:
url = 'https://www.indexmundi.com/map/?v=35&l=es'
html = requests.get(url).content
VIH = pd.read_html(html)[2]

In [162]:
VIH.head()

  Country  Birth rate (births/1,000 population)  Year
0  Angola                                    44  2017
1   Niger                                    44  2017
2    Mali                                    44  2017
3  Uganda                                    43  2017
4  Zambia                                    42  2017

# Birth rate
This entry gives the average annual number of births during a year per 1,000 persons in the population at midyear; also known as crude birth rate. The birth rate is usually the dominant factor in determining the rate of population growth. It depends on both the level of fertility and the age structure of the population.

In [159]:
url = 'https://www.indexmundi.com/map/?t=0&v=25&r=xx&l=en'
html = requests.get(url).content
Birth_rate = pd.read_html(html)[2]

In [161]:
Birth_rate.head()

  Country  Birth rate (births/1,000 population)  Year
0  Angola                                    44  2017
1   Niger                                    44  2017
2    Mali                                    44  2017
3  Uganda                                    43  2017
4  Zambia                                    42  2017

# Lic. en Física

In [163]:
url = 'http://fisica.ugto.mx/index.php/oferta-educativa-dci/oe-licenciatura/licenciatura-fisica-2016'
html = requests.get(url).content
Fisica = pd.read_html(html)

In [170]:
Creditos = Fisica[2]
display(Creditos)

,Distribución de créditos de la Licenciatura en Física,Distribución de créditos de la Licenciatura en Física.1
0,Créditos Obligatorios,163
1,Créditos del Área General,Mínimo 28
2,Créditos Optativos Disciplinares,Mínimo 35
3,Total mínimo,226

In [181]:
Plan = Fisica[3]
Plan

,0,1,2,3,4,5,6,7
0,Primera inscripción,Segunda inscripción,Tercera inscripción,Cuarta inscripción,Quinta inscripción,Sexta inscripción,Séptima inscripción,Octava inscripción
1,Matemáticas Superiores,Álgebra Lineal,Cálculo de varias variables,Análisis Vectorial,Ecuaciones Diferenciales Parciales,Mecánica Cuántica,Óptica,Optativa
2,Programación Básica,Cálculo Diferencial,Ecuaciones Diferenciales Ordinarias,Variable Compleja,Electromagnetismo,Mecánica Estadística,Taller de Investigación,Optativa
3,Física General,Cálculo Integral,"Fluidos, Ondas y Temperatura",Probabilidad y Estadística,Mecánica Analítica,Funciones Especiales,Laboratorio Avanzado,Optativa
4,Química General,Mecánica Clásica,Métodos Numéricos,Electricidad y Magnetismo,Termodinámica,Física Relativista,Temas Selectos de Física,Créditos del Área General
5,Desarrollo histórico de la Física Moderna,Herramientas informáticas y Gestión de la info...,Optativa,Optativa,Física Cuántica,Optativa,Optativa,NaN
6,Créditos del Área General,Créditos del Área General,Créditos del Área General,Créditos del Área General,Créditos del Área General,Créditos del Área General,Créditos del Área General,NaN